jobs:
  run-my-container:
    runs-on: ubuntu-latest
    steps:
      - name: Run my DockerHub image
        run: |
          docker pull carlamine/nourishai-app:latest
          docker run carlamine/nourishai-app:latest
